### ISSUE TITLE
Add an example using the widget

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/PaperBadger#108]
Script available here:
https://badges.mozillascience.org/widgets/paper-badger-widget.js

Let's add a section in the README on how to use the widget on your own site.

From @Alicole:

```html
<div class="badge-container">

     <script> 
     var conf={"article-doi": "10.1186/2047-217X-3-18", "class": "badge-container"};

     showBadges(conf);

     </script>
</div>
```

**Comment by Alicole** [comment]
Snippet of some example code that will display badges responsively, found below:

```
<!DOCTYPE html>
<html>
<head>
<title>Paper view snippet example | Paper Badger</title>
</head>	
<body>
<script src="https://code.jquery.com/jquery-1.8.2.min.js"></script>	
<script src="https://badges.mozillascience.org/widgets/paper-badger-widget.js"></script>
<div class="badge-container">

     <script> 
     var conf={"article-doi": "10.1186/2047-217X-3-18", "class": "badge-container"};

     showBadges(conf);

     </script>
</div>
</body>
</html>

```

May want to style container accordingly.

**Comment by hexplus** [comment]
I think the parameter key for the container class in that example above is incorrect. The correct is "container-class" instead of "class". (According line number 103 in paper-badger-widget.js, function showBadges).


If you want to use a custom container name, the code would be:


```html
<!DOCTYPE html>
<html>
<head>
<title>Paper view snippet example | Paper Badger</title>
</head> 
<body>

	<div class="my-container"></div>

	<script src="https://code.jquery.com/jquery-1.8.2.min.js"></script> 
	<script src="https://badges.mozillascience.org/widgets/paper-badger-widget.js"></script>
	<script> 
		var conf={"article-doi": "10.1186/2047-217X-3-18", "container-class": "my-container"};
		showBadges(conf);  
	</script>
</body>
</html>
```

Also is a good practice to have the scripts at the bottom (next to the </body> tag) in order to not block the load of the other elements of the website while the widget respond with the badges information.

**Comment by acabunoc** [comment]
Thanks @hexplus! I think we have also removed the jquery dependency since the last example.

Have you tested this out? Would you be up for writing a quick getting starting using this widget for our README?

**Comment by hexplus** [comment]
@acabunoc , I didn't noticed that Jquery is not required anymore, that's cool. Related the example it some times load the badges, some times not. 

With the README stuff, that would be great.

**Comment by acabunoc** [comment]
@aperala - this might a good issue for you!

Could you update our README to include documentation on how to use this widget? Happy to video chat :)

**Comment by aperala** [comment]
@acabunoc I took a stab at the README, but I'm not sure if this is the wording or the placement you'd want. (Sorry for the delay--I was at a presentation this evening).

<img width="907" alt="screen shot 2015-09-16 at 10 04 36 pm" src="https://cloud.githubusercontent.com/assets/12714591/9923122/f7f31c0a-5cbe-11e5-931e-05ea9f46e74b.png">

I'm on EST and could video chat in the morning if you'd like, or let me know of any edits/changes.
Thanks!

**Comment by acabunoc** [comment]
Hey @aperala - this looks like a good start! Have you made a pull request before? It would be helpful if you could make a pull request with your changes.

See the section on pull requests lower down:
https://guides.github.com/activities/contributing-to-open-source/#contributing

add me on skype if you want to find a time to chat: acabunoc

Thanks!

**Comment by acabunoc** [comment]
closing issue - example added by @aperala
