### ISSUE TITLE
AJAX replacement method for .get AJAX jquery functions.

### ISSUE THREAD

**Issue by Alicole** [mozillascience/PaperBadger#109]
Proposing to replace jquery function, with a general purpose vanilla Javascript method that works on latest browser versions, including IE 9. Currently due to AJAX CORS restrictions, widget not able to work on IE9. This change will fix that as well as removing Jquery dependency. Leaving only one more dependency to remove.

**Comment by Alicole** [comment]
@acabunoc I've added a new pull request, how can I commit my change so it's associated with this, as the branch now thinks everything is up to date?

**Comment by acabunoc** [comment]
this looks all updated in the current script! Closing issue :)
