### ISSUE TITLE
Look into emails going to spam

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/PaperBadger#119]
Publisher workflow all implemented! Many are ending up in spam, though. Looking into this.

**Comment by acabunoc** [comment]
Using http://www.emailspamtest.com -- the subject line may be considered 'spammy'

subject: 'Claim badges for your scholarly contributions!'

**Comment by jinankjain** [comment]
@acabunoc I ran the spam test I get a score of -1.9 and it is considered a safe mail. I don't think it will go into spam. http://www.emailspamtest.com/spam-test-results.aspx?f=348af88d-b854-4c30-9e7c-232eaccff094&s=eb015877-40f2-4ce9-8f68-8a9d08b70e44&c=6bce8f10-a5d8-4a28-9a4c-117dc20161b6. If still it goes into spam we could change the subject to Claim badges for your scholarly contributions from Mozilla Science Paper Badger. That sounds more authentic :p

**Comment by acabunoc** [comment]
Good suggestion @jinankjain :)
