### ISSUE TITLE
Add /count to more endpoints

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/PaperBadger#125]
Add documentation for:
- [x]  `/users/:orcid/badges/count`
- [x]  `/papers/:doi1/:doi2/badges/count`

Places to implement /count (& document):
- [ ] `/badges/count`
- [ ] `/badges/:badge/count`
- [ ] `/users/:orcid/badges/:badge/count`
- [ ] `/papers/:doi1/:doi2/badges/:badge/count`
- [ ] `/papers/:doi1/:doi2/badges/:orcid/badges/count`
- [ ] `/papers/:doi1/:doi2/badges/:orcid/badges/:badge/count`

**Comment by josmas** [comment]
all merged as per #190; closing this issue now.
