### ISSUE TITLE
Update example to load the widget non-blocking

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/PaperBadger#128]
```html
<script type="text/javascript">
   var script = document.createElement("script");
   script.type = "text/javascript";
   script.src = "https://badges.mozillascience.org/widgets/paper-badger-widget.js";
   document.body.appendChild(script);
</script>
```

Replace:

```html
<script src="https://badges.mozillascience.org/widgets/paper-badger-widget.js"></script>
```

This way, if badges.mozillascience.org goes down, it won't take your site with it!

**Comment by acabunoc** [comment]
Hey @aperala, are you interested in updating the README section you wrote with non-blocking code?

Let me know :)

**Comment by aperala** [comment]
will do!

**Comment by Alicole** [comment]
@acabunoc That snippet didn't work for us, however this one did, which we used before:
document.write(decodeURIComponent("%3Cscript src='https://badges.mozillascience.org/widgets/paper-badger-widget.js' type='text/javascript'%3E%3C/script%3E"));

**Comment by aperala** [comment]
@acabunoc Should I use the snippet that @Alicole has provided instead of what's above? 
I'm having the same result with that snippet-- the error message is showBadges() not defined.

**Comment by acabunoc** [comment]
that sounds like the file hasn't finished loading before you call
showBadges -- please test these out and find a good solution to add to the
readme :)

Thank you so much for helping us here, @aperala!

**Comment by aperala** [comment]
the snippet @Alicole worked for me, so I've replaced with that. Just submitted a PR.
