### ISSUE TITLE
Add ORCID oauth

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/PaperBadger#13]
Implement login using orcid authentication

Users should only be able to issue a badge for themselves (ideally, only if the journal has specified that they are the author):
https://github.com/mozillascience/PaperBadger/blob/master/web/app.js#L250

ORCID auth:
http://support.orcid.org/knowledgebase/topics/19248-authentication
http://orcid.org/blog/2014/04/29/beta-participants-wanted-public-authenticated-ids

**Comment by milapbhojak** [comment]
Let me start working on it.

**Comment by acabunoc** [comment]
Hey @milapbhojak --  that sounds great. Want to chat about the issue this week?

**Comment by milapbhojak** [comment]
@acabunoc sure, I've sent you an email about contact details :)

**Comment by rcpeters** [comment]
@milapbhojak https://github.com/ORCID/orcid-api-walkthrough/blob/master/server.js has a code snippet for authenticating an ORCID. Should start in on this issue?

**Comment by acabunoc** [comment]
Hey @milapbhojak, could you give us a pre-sprint update?

**Comment by rcpeters** [comment]
Here is even a simpler example: https://github.com/rcpeters/simple-orcid-auth-node 

Please let me know if I should take this on. Cheers,
Rob

**Comment by acabunoc** [comment]
Assigned to @rcpeters -- let us know when you're less busy, @milapbhojak!

**Comment by acabunoc** [comment]
closed in #42, #33, #48, #51 - with help from @rcpeters & @wjrsimpson. Thanks all!
