### ISSUE TITLE
Publisher interface - add a confirmation page

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/PaperBadger#130]
Instead of refreshing the page, add a confirmation that the form was submitted

https://badges.mozillascience.org/papers/new

**Comment by jinankjain** [comment]
@acabunoc When I tried to create a new paper and then I signed in using my ORCID ID, response returned was page not found.

Could you help me on that?

**Comment by acabunoc** [comment]
Hey @jinankjain -- right now only publishers are allowed to create papers. If you add yourself as a publisher in your local database you should be able to test this out.

**Comment by jinankjain** [comment]
Hey @acabunoc, I tried adding myself in local database also then also I was getting the same error

**Comment by jinankjain** [comment]
We can now close this issue.
