### ISSUE TITLE
Jan Hohner: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by janhohner** [mozillascience/PaperBadger#149]
I'm a web developer from Nuremberg, Germany. I've already added a pull request with an improved widget.<p><br><blockquote>This issue was created by @janhohner via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by acabunoc** [comment]
![hello!](http://i.giphy.com/IBMavwmu4KEEw.gif)
Welcome!

**Comment by janhohner** [comment]
Oh I didn't know this opens an issue here :D I'll close this.

**Comment by janhohner** [comment]
And thanks :)
