### ISSUE TITLE
Milap Bhojak: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by milapbhojak** [mozillascience/PaperBadger#15]
I also think the same way like As the research environment becomes more digital, we want to test how we can use this medium to help bring transparency and credit for individuals in the publication process.

Well, I can design product, UX, I'm writing code since 5 years so I can code. As I have 3 years of experience in open source community management, I can manage and become community growth hacker too :) 

looking forward to contribute in this project.<p><br><blockquote>This issue was created by @milapbhojak via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by acabunoc** [comment]
Thanks so much @milapbhojak -- I'll see you on the call tomorrow! I hope the time isn't too inconvenient for you.
