### ISSUE TITLE
Footer is not sticky (About and Issue)

### ISSUE THREAD

**Issue by wizgothic** [mozillascience/PaperBadger#151]
Confirmed on all devices and browsers.

How to fix this- in main.css:

.footer {
    position:fixed;
    bottom:0;
    background: #111;
}

**Comment by acabunoc** [comment]
Thanks so much for this @wizgothic!

I'll label this good first bug -- happy to see a PR from a new contributor :)

**Comment by acabunoc** [comment]
Addressed (& being discussed) in #152
