### ISSUE TITLE
Remove filtering badges

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/PaperBadger#16]
In several places, we fetch a set of badge instances from badgekit-api, then filter the results for the badges we actually want. We should be able to fetch just the ones we're looking for from badgekit-api.

* ORCID & badge (currently fetch by ORCID, filter by badge)
https://github.com/mozillascience/PaperBadger/blob/master/src/app.js#L106

* DOI & badge (currently fetch by badge, filter by DOI)
https://github.com/mozillascience/PaperBadger/blob/master/src/app.js#L132

* DOI & ORCID (currently fetch by ORCID, filter by DOI)
https://github.com/mozillascience/PaperBadger/blob/master/src/app.js#L144

* ORCID, DOI & badge (curently fetch by ORCID, filter by DOI & badge)
https://github.com/mozillascience/PaperBadger/blob/master/src/app.js#L156

**Comment by yati-sagade** [comment]
The links are broken -- should be `.../src/app.js` (s/web/src/)

**Comment by acabunoc** [comment]
Thanks @yati-sagade!! Updated the links :)
