### ISSUE TITLE
Add live examples of Paper Badger to the README

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/PaperBadger#161]
Two publishers are using Paper Badger in production! ORCID also displays badges! Add links to these in the README so people can see how it works live.

Examples listed in this blog post:
https://www.mozillascience.org/contributorship-badges-for-science-view-them-now

**Comment by jinankjain** [comment]
I was thinking that we could add a sub heading something like current users and add a link or snapshot from those websites that are mentioned in the blog post.

@acabunoc  First thing we have to decide that what would be the sub heading and should we just url or url along with snapshot.

**Comment by acabunoc** [comment]
Hey @jinankjain thanks for chiming in :)

Your ideas sound great -- I hadn't considered a 'current users' subheading or screenshots. If you're interested, it would be nice to see these in a pull request and I can comment there if I have other changes I'd like to see!
