### ISSUE TITLE
Refactoring getBadges / getTheBadges

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/PaperBadger#171]
In both `/routes/papers/index.js` and `/routes/users/index.js`, there are a lot of similarities between `getBadges` and `getTheBadges`. Refactor to reuse code.

https://github.com/mozillascience/PaperBadger/blob/master/src/routes/papers/index.js
https://github.com/mozillascience/PaperBadger/blob/master/src/routes/users/index.js

More details: https://github.com/mozillascience/PaperBadger/pull/168#discussion_r55863246

**Comment by AndreyK729** [comment]
I want to participate in GSoC, and I would like to help Mozilla Science Lab with [Contributorship Badges for Science](https://github.com/mozillascience/PaperBadger/issues/159). Please, assign me to this issue, so I can prove myself worthy.

**Comment by acabunoc** [comment]
Hey @AndreyK729! You're welcome to send over a pull request with your updates on the issue! Happy to answer any questions you may have. You may find our gitter chat useful: 

[![Join the chat at https://gitter.im/mozillascience/PaperBadger](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/mozillascience/PaperBadger?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by jinankjain** [comment]
@acabunoc I think you are talking about the getTheBadges function in both of them ?

**Comment by jinankjain** [comment]
@acabunoc Am I correct ?

**Comment by geeeeeeeeek** [comment]
@acabunoc still need a pull request? This issue has been opened for a long time. If has not been resolved, I will work on this.

**Comment by acabunoc** [comment]
Hey @jinankjain & @geeeeeeeeek - yes both getTheBadges and getBadges functions in both of them -- all four are similar.

I'd like unit tests first before these changes go in.

**Comment by josmas** [comment]
closing this one after merging #183 and #186
