### ISSUE TITLE
Amit Kumar Jaiswal: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by amitkumarj441** [mozillascience/PaperBadger#182]
I am a IIIrd year undergraduate of Computer Science currently pursuing my Bachelor in B.Tech and I'm an active open source contributor and Mozillian and having done academic projects in Database where my work involved as a Frontend and Backend developer, that's why this project amuse me to form my interest in particular. I want to develop digital badges for publishers to integrate code and scientific software into the scholarly workflow. I already submitted my GSoC proposal for this project. If I have given a chance then I will be proven asset to your organization.<p><br><blockquote>This issue was created by @amitkumarj441 via <a href='https://mozillascience.org/collaborate'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by acabunoc** [comment]
Thanks @amitkumarj441! You're welcome to jump in on any of the issues :)
