### ISSUE TITLE
Karthic Keyan: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by hellokarthic** [mozillascience/PaperBadger#185]
<p><br><blockquote>This issue was created by @hellokarthic via <a href='https://mozillascience.org/collaborate'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by acabunoc** [comment]
Hey @hellokarthic! Welcome! 

Is there anything in particular you're interested in working on? Welcome to the project 🎉
