### ISSUE TITLE
Adding RSS views 

### ISSUE THREAD

**Issue by amitkumarj441** [mozillascience/PaperBadger#188]
Adding RSS views will enable users to connect with the service independent of "IF THIS THEN THAT" (IFTTT).

Our implementation approach for PaperBadger uses some credentials (like a channel-key which is kept secret), so the page just shows with a GET request should be: 

`{
  "errors": [
    {
      "message": "Unauthorized"
    }
  ]
}`

I will use a similar approach in integrating the feature for research data, this will require me to write a web service application in Python (running on the Flask framework) to read data from data using the PaperBadger and PaperBadger API on a regular basis.

**Comment by josmas** [comment]
I don't fully understand the goal here; @acabunoc is an RSS feed something identified as a need for the project? I don't see anything in the roadmap (#17) with regards to this.

@amitkumarj441 can you explain a little more what you are trying to achieve? Or the errors you are seeing for credentials. There's a lot of stuff in the message above (IFTTT, Flask, APIs, channel-key???) that seems unrelated to PaperBadger; sorry but I am a bit confused.

**Comment by amitkumarj441** [comment]
Hi @acabunoc ,

@josmas , I actually want to integrate vast research data which support PaperBadger by implementing post and get request and the above mentioned things in my issue.
Please have a look over my created issue.
Let me know if you need further explanation in this context.

Thank you
Amit Kumar Jaiswal

**Comment by josmas** [comment]
Hi @amitkumarj441 I'm really sorry, but it is Monday and I am a bit slow :D

Can you piece it a little for me? You want an RSS feed of what kind of data? and also, _get_ and _post_ of specifically what kind of information?
How are you planning to integrate, and what does _vast research data which support PaperBadger_ mean in your context? Thanks!

**Comment by acabunoc** [comment]
Hey @amitkumarj441, I'm also confused! Do you want to broadcast every time someone gets a badge?

**Comment by josmas** [comment]
@amitkumarj441 If it is OK with you, I am going to close this issue for now. I am concerned about potential participants getting sidetracked during the Sprint.

Once you have a clear picture of what you want to do, please do reopen again. Thanks!
