### ISSUE TITLE
Add testing

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/PaperBadger#19]
Use Mocha!

- [x] set up test framework: @aid29
    - [x] #25, #26 - @aid29 
- [x] write tests for PaperBadger api: @audy / @aid29

**Comment by acabunoc** [comment]
@audy may look into this during the sprint

**Comment by acabunoc** [comment]
Mocha: http://mochajs.org/

**Comment by audy** [comment]
We'll also need to mock HTTP responses somehow. Is there a node.js thing for that? Google-first-hit says http://sinonjs.org/.

**Comment by audy** [comment]
@aid29 I added Mocha over on here https://github.com/audy/PaperBadger/tree/add-test-framework. It's only a few lines of code so I won't be heartbroken if you don't use it.

**Comment by ibjhb** [comment]
If you need to mock HTTP/API responses, you might want to check out:
https://github.com/typicode/json-server

**Comment by acabunoc** [comment]
Thanks @ibjhb -- helpful :)

**Comment by audy** [comment]
@aid29 I'm working on this but the internet says there are a thousand different ways.

Frequently, I see people running the server and sending it HTTP requests with superagent. This is different from what I'm used to with Ruby (you test the HTTP methods without running the actual HTTP server). Would you recommend this approach?

**Comment by aid29** [comment]
Hi @audy , I think we can start by having some integration tests for testing the endpoints with real http server (maybe ask @acabunoc some golden data), then have some unit tests for the logic calling the Mozzila Badge API which dependent on #26

**Comment by audy** [comment]
I need to do some restructuring so I can unit test methods inside of `src/app.js`.

This is my idea:

- `src/routes.js` - express.js routing
- `src/helpers.js` - misc functions used throughout the app like `emailFromORCID` for example.

I need to rewrite `helpers.js` as a module.

instead of

```javascript
module.exports = function(config) {
  function foo(bar) {
    return 'baz';
  };
};
```

I would need to write

```javascript

module.exports = function(config) {
  foo: function(bar) {
    return "baz";
  };
};
```

So that I am able to access these functions from my tests.

How about I send a PR for the basic testing skeleton w/o any tests, then work on what I have just proposed in another branch, then start adding actual tests after the first two things are done?

**Comment by acabunoc** [comment]
@JJ - writing tests with @audy might be a good place to jump in :)

**Comment by audy** [comment]
Good place for "golden" data https://github.com/mozilla/badgekit-api-client/tree/master/docs

**Comment by acabunoc** [comment]
?

https://github.com/mozillascience/PaperBadger/blob/master/src/app.js#L7

**Comment by acabunoc** [comment]
So.. that got outdated quickly
https://github.com/mozillascience/PaperBadger/blob/master/src/app.js#L11

**Comment by aid29** [comment]
@audy Nice job for the setup and init tests ;)
Currently pbm is the npm script "test"  is failed because Cannot find module 'supertest'. What is the plan for that? Can I do the fix?

**Comment by acabunoc** [comment]
Hey @aid29! Did you run `npm install`? There are a few new modules :)

**Comment by aid29** [comment]
I forgot it :p

**Comment by acabunoc** [comment]
It happens :)

**Comment by aid29** [comment]
@acabunoc As #25 #26 are both close, can we close this one as well?
