### ISSUE TITLE
Error trying to run 'npm start' ... might be something silly I am pretty new to node

### ISSUE THREAD

**Issue by univ3573** [mozillascience/PaperBadger#197]
npm ERR! Error: ENOENT, open '/home/data/open_science/PaperBadger/scripts/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.0.4-201.fc21.x86_64
npm ERR! command "node" "/bin/npm" "start"
npm ERR! cwd /home/data/open_science/PaperBadger/scripts
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.3.6
npm ERR! path /home/data/open_science/PaperBadger/scripts/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/data/open_science/PaperBadger/scripts/npm-debug.log
npm ERR! not ok code 0

**Comment by univ3573** [comment]
> PaperBadger@0.1.1 start /home/data/open_science/PaperBadger
> npm-run-all --parallel server watch:js


> PaperBadger@0.1.1 server /home/data/open_science/PaperBadger
> node src/index.js


> PaperBadger@0.1.1 watch:js /home/data/open_science/PaperBadger
> npm run build:js -- --watch

npm ERR! Error: ENOENT, open '/home/data/open_science/PaperBadger/node_modules/build:js/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.0.4-201.fc21.x86_64
npm ERR! command "node" "/bin/npm" "run" "build:js" "--" "--watch"
npm ERR! cwd /home/data/open_science/PaperBadger
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.3.6
npm ERR! path /home/data/open_science/PaperBadger/node_modules/build:js/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/data/open_science/PaperBadger/npm-debug.log
npm ERR! not ok code 0
npm ERR! weird error 34
npm ERR! not ok code 0
npm ERR! weird error 143
npm ERR! not ok code 0
ERROR: watch:js: None-Zero Exit(1);
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by josmas** [comment]
This turned out to be an old version of node and npm. Closing. Feel free to reopen if issues persist.
