### ISSUE TITLE
using env.docker does not read the right values for env variables

### ISSUE THREAD

**Issue by drammock** [mozillascience/PaperBadger#199]
many tests fail with `Get error from return Badges NotAuthorizedError: Invalid token signature` when the environment file is named `env.docker` rather than `.env`.  `cp env.docker .env` is a temporary workaround.  @josmas thinks this might be related to how habitat is being used.

**Comment by josmas** [comment]
I do indeed! The thing is that the docker setup used to be used only for quickly running things, not for development, and it used to copy the whole sources folder into the container. It does not do that anymore, so the env.docker file is getting lost somehow. We probably need to get rid of it and change the setup instructions in the readme, but have to look at it with a bit more time!

**Comment by josmas** [comment]
@drammock just checked this one and it works for me if I run the tests inside the container. It won't work if the tests are run outside the container. You can connect to the container with `docker exec -it CONTAINER_NAME_OR_HASH /bin/bash` and then `npm test`. At times they do timeout, but the variables seem to be read correctly (they will not if you try to run the tests from the host).

**Comment by josmas** [comment]
I think that in any case, we can simplify this by getting rid of _env.docker_ and just asking everyone to use _.env_. That way it should work both outside and inside the container.

**Comment by acabunoc** [comment]
+1 simplifying to just `.env` if we can

**Comment by drammock** [comment]
@josmas confirmed, tests pass within the container.
