### ISSUE TITLE
Jane Frazier: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by mignon1915** [mozillascience/PaperBadger#20]
<p><br><blockquote>This issue was created by @mignon1915 via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by acabunoc** [comment]
Hey @mignon1915, welcome to the project!

Are you free to chat for a bit to see where you'd like to help out? Let me know if you have any questions :) abigail [at] mozillafoundation.org

One thing that would be very helpful is if you could go through the [Getting Started](https://github.com/mozillascience/PaperBadger#getting-started) steps and let me know if it worked for you.

**Comment by acabunoc** [comment]
We're chatting via email, closing issue
