### ISSUE TITLE
Move badges.mozillascience.org to science.mozilla.org/badges

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/PaperBadger#207]
With the new site, we should move the badges over to `science.mozilla.org/badges`. Let's sync up with @cadecairos to see what we'll need to make the switch.

It sounds like we can route the requests through cloudfront to forward /badges/* to our app. We might have to move all the routes on the heroku app to /badges.

@josmas can you sync up with @cadecairos and figure out what exactly we need to do? I can help with the routes stuff if we have to move them.

**Comment by josmas** [comment]
sure, I don't have much context for this, but can sync up. @cadecairos, can you let me know when is good to chat? thanks!

**Comment by cadecairos** [comment]
@josmas woops, this got lost in the ever expanding void of my inbox.

I'm free to chat for the rest of my morning.

**Comment by cadecairos** [comment]
It can probably wait a couple days at most, but the certificate expires in 13 days. If we can't get the badges moved off that sub-domain, I'll have to keep it as a SAN on the SSL certificate (which isn't the end of the world)

**Comment by josmas** [comment]
OK, I'll ping you in a few hours; we may have to bring in @acabunoc as I might not have enough details. Talk to you in a bit!

**Comment by cadecairos** [comment]
@acabunoc @josmas 

The more I think about this, the less I want it to happen. 

The primary detractor for me is the fact that we'd still need to add badges.mozillascience.org to the certificate so that it gets redirected to the new site.

**Comment by acabunoc** [comment]
@cadecairos I'll leave this decision up to you! Whatever you think is best, happy to implement what you need

**Comment by josmas** [comment]
The certificate will be renewed as is, so closing this one now. Thanks @cadecairos !
