### ISSUE TITLE
dj7777: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by dj7777** [mozillascience/PaperBadger#21]
I am a Computer Science student.<p><br><blockquote>This issue was created by @dj7777 via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by acabunoc** [comment]
Hey there @dj7777, welcome :)

Are you free to chat for a bit to see where you'd like to help out? Let me know if you have any questions :) abigail [at] mozillafoundation.org

One thing that would be very helpful is if you could go through the [Getting Started](https://github.com/mozillascience/PaperBadger#getting-started) steps and let me know if it worked for you.

**Comment by acabunoc** [comment]
@dj7777 and I spoke via Skype. He'll contribute during the sprint. Closing issue for now.
