### ISSUE TITLE
Build interface for the publisher

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/PaperBadger#22]
Part of #18: Building the badge issuing process
**Help wanted: Designers, Developers, Input**

Our first prototype won't attempt to integration with the Publishers submission system. Instead, Publishers will manually enter article info in a form. The functionality of the form is handled in #23.

They should be able to input:
1. DOI of the paper
2. Author emails
3. Author ORCIDs (optional)

To Do:

- [x] *[Input]* Decide how to authenticate publishers. Is this required for MVP?
- [x] *[Dev]* Implement publisher authentication (if needed)
- [x] *[Design]* Design form. Inputs: paper DOI, author emails
- [x] *[Dev]* Build form
- [x] Submission function handled in #23
- [x] Launch!

Questions:
* Should pubilshers log in before they can access this form in our MVP? How will we know they are publishers?

**Comment by iamjessklein** [comment]
As per issue #24 , are the authors endorsing the badge and by doing so, supplying some form of evidence?  Also, what does DOI mean? #noobquestion

**Comment by acabunoc** [comment]
DOI: Digital Object Identifier

In this case, it's used as a unique identifier for a paper, in for the form of a url and used as evidence:
example DOI:
dx.doi.org/10.1186/s13059-015-0705-2

@iamjessklein - sorry there's a lot of domain knowledge I've completely forgotten to define here! *really* great questions

**Comment by acabunoc** [comment]
![submit-paper](https://cloud.githubusercontent.com/assets/617994/8824863/c5f7f458-3047-11e5-83da-dd5e7b7dd898.gif)

Form prototype ^

Currently in review. Added dynamic inputs for multiple authors.

**Comment by aid29** [comment]
Nice one!

Another thought, as I have already saw some articles with > 8 authors, maybe have a option to input a list of email address (separated by comma) ?

**Comment by acabunoc** [comment]
@aid29 - that makes a *lot* of sense

**Comment by acabunoc** [comment]
With a textarea instead:

![screen shot 2015-07-22 at 14 07 06](https://cloud.githubusercontent.com/assets/617994/8833079/f929bf4a-307a-11e5-8cbd-153760c3d46f.png)

/cc @akenall -- you'd be the first person using this form. Any suggestions?

**Comment by akenall** [comment]
Looks good!
