### ISSUE TITLE
Build interface for the Authors

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/PaperBadger#24]
Part of #18: Building the badge issuing process
**Help wanted: Design, Development**

Following #23, where authors are sent a unique link (currently http://paperbadger.herokuapp.com/issue), this link should be associated with a DOI (& email address?). Once authenticated, the unique link will lead to a form that allows authors to select their roles on a paper. This will trigger issuing the badges. Authors can only issue badges to their own ORCID for papers that Publishers have confirmed they authored.

When an author visits the link (http://paperbadger.herokuapp.com/issue):
* If they're not logged in, log in via ORCID auth to get ORCID
* Display a list of roles authors can select 

When the form is submitted:
* A badge is issued to the authors' ORCID for each role they've selected

To do:
- [x] *[Dev]* link redirects to ORCID auth if not logged in
- [x] *[Dev]* prefill user' ORCID
- [x] *[Dev]* prefill DOI from unique link
- [x] *[Dev]* on submit, **one** badge is issued to the author's ORCID for a role they've selected
- [x] *[Dev]* allow for multiple badges to be selected and issued
- [x] *[Design]* Allow user to easily select multiple badges. Add badge descriptions somewhere.
- [x] *[Dev]* Build new design
- [x] Launch

**Comment by audy** [comment]
Is this going to go through the badgekit API or will this require building a DB for PaperBadger?

**Comment by acabunoc** [comment]
badgekit api -- basically replace what we currently have under /issue
http://paperbadger.herokuapp.com/issue/

**Comment by iamjessklein** [comment]
@acabunoc to clarify, is the author self issuing a badge and then the publisher is kind of like endorsing that the badge is legit?

**Comment by acabunoc** [comment]
@iamjessklein it's the other way around, really.

1. The publisher notifies us when they have a new paper and who the authors are
2. We notify the authors, they can self issue badges on *that* paper only

Thanks for helping clarify!

**Comment by acabunoc** [comment]
Hey @lupon - saw your comment [here](https://github.com/mozillascience/PaperBadger/issues/2#issuecomment-136962765). Would love your help with some of our interfaces. What are you interested in?

**Comment by Lupon** [comment]
Hi Abigail,

I'm a UX and UI designer. Passionate about design and innovation. I've been
working as a creative director in a big advertising agency in Israel, but
for the last 2 years I've been working with statups (web and mobile
applications mostly). Your project is interesting. Maybe I can give a hand.
Would you like to see my work?



*Simon Adar, CEO*     |   +1 201 253 6313   |   simon@code-ocean.com   |
www.code-ocean.com

**Comment by Lupon** [comment]
Hi Abigail,

I'm a UX and UI designer. Passionate about design and innovation. I've been
working as a creative director in a big advertising agency in Israel, but
for the last 2 years I've been working with statups (web and mobile
applications mostly). Your project is interesting. Maybe I can give a hand.
Would you like to see my work?

**Comment by acabunoc** [comment]
Hey @Lupon - I'd love your help! Are you free to chat today or Friday?

Skype: acabunoc
time zone: EDT

**Comment by Lupon** [comment]
Sorry for the absence . Had some medical issues to attend.
Maybe it's not the best time for me to commit to a new project. I'll keep
following your project and be in touch when I get some free time.

Good luck, Asaf

*Simon Adar, CEO*     |   +1 201 253 6313   |   simon@code-ocean.com   |
www.code-ocean.com
