### ISSUE TITLE
Build express http app in a separated js class

### ISSUE THREAD

**Issue by aid29** [mozillascience/PaperBadger#25]
So we can start easily the http app with different dependencies or configuration in the test scenarios

**Comment by acabunoc** [comment]
Thanks @aid29 - this sounds good, like I said in the email, I placed app.js in /web with a refactor in mind. 

Could you run this one?

**Comment by aid29** [comment]
ok, i will put all the js sources in "src" folder.

**Comment by acabunoc** [comment]
Hey @aid29 - could you leave them in /web? All the linters are configured for that. If you move them to /src can you update the scripts?
https://github.com/mozillascience/PaperBadger/blob/master/package.json#L6

**Comment by aid29** [comment]
@acabunoc Sure, i have updated all the scripts in package.json. I have pushed the changes to the issue_25 branch on my fork. Can you have a look? Thanks.

**Comment by acabunoc** [comment]
Thanks @aid29! I made a pull request for you: https://github.com/mozillascience/PaperBadger/pull/27

Here's a guide for next time: https://guides.github.com/activities/hello-world/#pr

I'll take a look today :)

**Comment by acabunoc** [comment]
Fixed by @aid29 in #27
