### ISSUE TITLE
Build badgeKit API client

### ISSUE THREAD

**Issue by aid29** [mozillascience/PaperBadger#26]
Extract the codes using the badgeKit API to a separated client class, make easy to test this client against real api server or a fake one.

**Comment by acabunoc** [comment]
Thanks for this too @aid29!

**Comment by aid29** [comment]
No problem! Like to work on this.

**Comment by aid29** [comment]
But may not finished before Mozilla Global Sprint, what is your plan on Sprint?

**Comment by acabunoc** [comment]
During the sprint, I'd like to finish everything in Short Term on the Roadmap: #17 

Just to clarify, this issue is separating the badgekit code out of app.js into a separate module? We are technically already using badgekit-api-client (http://github.com/mozilla/badgekit-api-client) to interface with the badgekit-api

**Comment by aid29** [comment]
Yes, that's right. We can call it "BadgerService" or something which use badgekit-api-client. 
In your sort term plan, it looks like a lot of works...

**Comment by aid29** [comment]
@acabunoc I found this request parameter :badges is not used in this endpoint. https://github.com/mozillascience/PaperBadger/blob/master/src/app.js#L279

**Comment by aid29** [comment]
Hi @audy "nock" is great! 

Where you find the url "/systems/badgekit/badges?archived=any" which you have faked for calling by BadgeClientApi?

**Comment by acabunoc** [comment]
@aid29 that should definitely be 'users' not ':badges'...

**Comment by audy** [comment]
> Where you find the url ...

I don't recall. I think I looked at the tests for badgekit-api.

**Comment by aid29** [comment]
@audy when I tried to stub this endpoint "/systems/badgekit/badges?archived=any" with some fake JSON or real badge JSON, the badge Client always return '{}' 

If you don't 'nock' this endpoint, definitely the Client return a error.

Do you have successfully cheat badge Client to return some JSON data?

**Comment by aid29** [comment]
@audy when I tried to stub this endpoint "/systems/badgekit/badges?archived=any" with some fake JSON or real badge JSON, the badge Client always return '{}' 

If you don't 'nock' this endpoint, definitely the Client return a error.

Do you have successfully cheat badge Client to return some JSON data?

**Comment by aid29** [comment]
I think I need read more BadgeClientAPi source code to understand what happen there, maybe try a integration test with real Badge server in this issue first.

**Comment by acabunoc** [comment]
Hey @aid29, this might help you:
https://github.com/mozilla/badgekit-api-client

Also: https://github.com/mozilla/badgekit-api/tree/master/docs

Thanks for looking into this!

**Comment by acabunoc** [comment]
Also, this is the badgekit-api instance we have running / we are using on http://paperbadger.herokuapp.com/:

http://badgekit-api-sciencelab.herokuapp.com/

We successfully fetch / store badges from there. Can you make sure you have the correct environment variables?

**Comment by aid29** [comment]
@acabunoc When I connect the project to http://badgekit-api-sciencelab.herokuapp.com/, everything is worked.

But I think audy's solution is cool, so I tried to make the badgekit-api-client talking to a "nock" http server in the test. but it's failed. badgekit-api-client always return a empty json.

I will start writing the tests against the http://badgekit-api-sciencelab.herokuapp.com/

Better to change the tests running against a local badgekit server.

**Comment by aid29** [comment]
Hi @acabunoc I have pushed my branch for #26, please have a look.
here is my notes:
- I finally choice to write directly the integration tests (run against the real OpenBadges server) to cover all our endpoints. Sorry, @audy You can't run all the tests locally for the moment. I think we can start one local Badges server in our build script lately to run all our tests on local. 

- I got a problem with "Habit" to load the different environment variables in different tests, so I comment out the api.js in the branch.

- I have built a test for create the badge, but it's see not working? the response return is empty. I commented this test for the moment.

All the feedback or question are welcome, thanks.

**Comment by acabunoc** [comment]
Hey @aid29! Can you make a pull request?

https://guides.github.com/activities/hello-world/#pr

Thanks!

**Comment by audy** [comment]
> I think we can start one local Badges server in our build script lately to run all our tests on local.

I agree. This is a better approach.

**Comment by aid29** [comment]
@acabunoc Sorry, forgot that, just done.

**Comment by aid29** [comment]
The build are failed on CI https://travis-ci.org/mozillascience/PaperBadger/builds/67547510
I think the test running base on the configs load from .env file which don't exist in project.
The problem is we don't want to commit the secret code to the source. Maybe we need block this until we have a local Badges server setup.

**Comment by audy** [comment]
You can encrypt the key and store it in `.travis.yml`: http://docs.travis-ci.com/user/encryption-keys/. Let me know if you need help.

**Comment by aid29** [comment]
Thanks @audy 
But looks like it have the restriction about "encrypted environment variables are not available for pull requests from forks." Let's wait @acabunoc to do this :-p

**Comment by acabunoc** [comment]
Hey both! I added the relevant environment variables to Travis -- not sure if this is the best approach

BADGES_ENDPOINT
BADGES_KEY
BADGES_SECRET
BADGES_SYSTEM

**Comment by acabunoc** [comment]
resolved with #67!
