### ISSUE TITLE
Use simple-oauth2 from npm

### ISSUE THREAD

**Issue by audy** [mozillascience/PaperBadger#37]
#33 needs to use a special branch of simple-oauth2 until this issue is resolved https://github.com/andreareginato/simple-oauth2/pull/38.

**Comment by jinankjain** [comment]
@audy, @acabunoc  we are already using simple-oauth2 from npm. We could close this issue now

**Comment by acabunoc** [comment]
true! closing :)

Thanks for the keen eye @jinankjain
