### ISSUE TITLE
active PaperBadger on Travis

### ISSUE THREAD

**Issue by audy** [mozillascience/PaperBadger#39]
I need an admin to activate PaperBadger on Travis [here](https://travis-ci.org/profile/mozillascience).

**Comment by acabunoc** [comment]
on it. I've never used Travis before

**Comment by acabunoc** [comment]
I think we're good!

**Comment by audy** [comment]
Yep. URL is [https://travis-ci.org/mozillascience/PaperBadger](https://travis-ci.org/mozillascience/PaperBadger)

**Comment by acabunoc** [comment]
\o/

**Comment by acabunoc** [comment]
oh man, travis is so cool
