### ISSUE TITLE
Jennifer Seiler: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by jaseiler** [mozillascience/PaperBadger#4]
<p><br><blockquote>This issue was created by @jaseiler via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by acabunoc** [comment]
Hey @jaseiler, welcome to the project!

I'm about to release a proposed timeline and development plan. Are you interested in anything in particular?
