### ISSUE TITLE
Load data from Amye in database

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/PaperBadger#43]
I got some good data from @akenall @ BMC for a few of their test papers. Will load in so we can play with some real data! (and not just badges assigned to me for everything...)

**Comment by acabunoc** [comment]
In light of #56, I'll wait till we have real ORCIDs before loading in real data. Might be confusing to have real + test data together.

**Comment by akenall** [comment]
Thanks, Abby! I’ve just had a look at the spreadsheets this morning and more authors have completed their parts, so it looks like the delay has given us time to get better data. Let me know if you notice anything with the data and I need to go back to the authors.

Great to see the project making progress!

Amye

Amye Kenall
Associate Publisher
Health and Applied Sciences and Open Data
Floor 6, 236 Gray's Inn Road
London, WC1X 8HL
Tel: +44 20 3192 2768
Fax: +44 20 3192 2011
amye.kenall@biomedcentral.com<mailto:amye.kenall@biomedcentral.com>
http://www.gigasciencejournal.com/

Follow BioMed Central:

[cid:image001.jpg@01CB3975.0EFB53E0]<http://twitter.com/BioMedCentral>

[Facebook]<http://www.facebook.com/BioMedCentral>

[cid:image003.jpg@01CB3975.0EFB53E0]<http://www.linkedin.com/groups?gid=2807240>

[YouTube]<http://www.youtube.com/user/BioMedCentral>

@OpenDataBMC<https://twitter.com/OpenDataBMC>
@AmyeKenall<https://twitter.com/AmyeKEnall>

**Comment by acabunoc** [comment]
loaded in! deleted existing data.

You can view them by clicking around here:
http://paperbadger.herokuapp.com/
