### ISSUE TITLE
fahim: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by fahimfana** [mozillascience/PaperBadger#5]
<p><br><blockquote>This issue was created by @fahimfana via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by acabunoc** [comment]
Hey @fahimfana -- sorry for the delayed response, I missed this earlier!

We'd love to have you help out! One thing that would be very helpful is if you could go through the [Getting Started](https://github.com/mozillascience/PaperBadger#getting-started) steps and let me know if it worked for you.

Thanks @fahimfana, welcome :)
