### ISSUE TITLE
Integration with ORCID production server

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/PaperBadger#56]
For our MVP, we'd like to test this out with real users and their real ORCIDs. Work with the ORCID group to use production data.

---- original issue ----
When I log in to ORCID via https://sandbox.orcid.org/oauth/signin, I get a different ORCID then when I log into the main site.

sandbox:
0000-0002-4134-9255

main site:
0000-0003-4959-3049

Not sure if this is specific to me, or if we need to update something to use users current ORCIDs to issue badges. @rcpeters & @wjrsimpson any ideas?

**Comment by rcpeters** [comment]
Sandbox is separate 100% from production. We would have to go through a
formal review before issuing credentials. Should we set up a call for later
this week?

Cheers,
Rob

On Fri, Jun 5, 2015 at 2:16 PM, Abigail Cabunoc Mayes <
notifications@github.com> wrote:

> Assigned #56 <https://github.com/mozillascience/PaperBadger/issues/56> to
> @rcpeters <https://github.com/rcpeters>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozillascience/PaperBadger/issues/56#event-323991064>.
>



-- 
Robert Peters
info@rcpeters.com
805.440.9056

**Comment by acabunoc** [comment]
Ah, that makes sense :) I'll reach out Monday to schedule a call

**Comment by lpaglione** [comment]
Hi -- straight-forward to get production credentials - we just need to decide who's ORCID account they will be registered to. The process for getting those credentials can be found here: http://members.orcid.org/api/accessing-public-api

**Comment by acabunoc** [comment]
Apply for developer credentials!

http://support.orcid.org/knowledgebase/articles/343182-register-a-client-with-the-public-api

**Comment by acabunoc** [comment]
Filled out this form: https://orcid.org/content/register-client-application-production-trusted-party. Waiting.

**Comment by rcpeters** [comment]
That's for paid members, see
http://support.orcid.org/knowledgebase/articles/343182-register-a-client-with-the-public-api
for
the free public credentials.

On Fri, Aug 28, 2015 at 1:10 PM, Abigail Cabunoc Mayes <
notifications@github.com> wrote:

> Filled out this form:
> https://orcid.org/content/register-client-application-production-trusted-party.
> Waiting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozillascience/PaperBadger/issues/56#issuecomment-135876248>
> .
>



-- 
Robert Peters
info@rcpeters.com
805.440.9056

**Comment by acabunoc** [comment]
Thank you @rcpeters!

**Comment by acabunoc** [comment]
done!
