### ISSUE TITLE
Import badgekit-api MySQL database for testing

### ISSUE THREAD

**Issue by audy** [mozillascience/PaperBadger#65]
for #19.

**Comment by audy** [comment]
I can import the dump that @acabunoc sent me just by running

```sql
mysql> create database test;
```

and

```sh
mysql test < database.sql
```

The question I have now is: do I go ahead and setup MySQLl+Travis now even though we don't have a local paperbadger-api server running yet?

**Comment by acabunoc** [comment]
I don't know if we need to actually run badgekit-api and mysql locally -- it's pretty large scope.

Can we mock the responses we would get from http://badgekit-api-sciencelab.herokuapp.com/ to test? I guess that's similar to what nock would do. Let me know your thoughts.

**Comment by aid29** [comment]
These days we use Docker? :p

**Comment by acabunoc** [comment]
Hey @audy -- any update on this?

**Comment by audy** [comment]
> I don't know if we need to actually run badgekit-api and mysql locally -- it's pretty large scope.

Then we can just close this. I thought it would be better because we can test future versions of `badgekit-api` without having to mock new responses.

**Comment by audy** [comment]
I canlook at this in more detail after 7/27.

**Comment by acabunoc** [comment]
Ooohh, I see your point. tbh, I don't think badgekit-api will change much considering project status. I'll keep this open as a discussion point, but I won't tie it to a milestone.

Have fun writing/defending! Good luck :)

**Comment by audy** [comment]
I recently stumbled across the [sepia](https://github.com/linkedin/sepia) library for node.js that might be useful here.

Basically, you run tests once against a real API and sepia records and saves all of the responses. Then, when you run the tests in the future, the saved responses (if present) are used. If the API changes, all you have to do is run the real API requests again and commit the responses.

**Comment by josmas** [comment]
This was closed automatically with the merge. It would still be interesting to use sepia or some other recording mechanism but for now, the test server will do.
