### ISSUE TITLE
Add encrypted environment variables to .travis.yml

### ISSUE THREAD

**Issue by aid29** [mozillascience/PaperBadger#70]
[Edit from @acabunoc]

Add encrypted variables to .travis.yml
File to edit: https://github.com/mozillascience/PaperBadger/blob/master/.travis.yml
Instructions: http://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables
Mentor: @acabunoc

----- original issue -----
We notice some TravisCI build don't setup the environment variables before running the tests. That make the tests failed. Looks like this happen only for the builds running on PR.
The failed builds example:
https://travis-ci.org/mozillascience/PaperBadger/builds/70191487
Same code passed example:
https://travis-ci.org/mozillascience/PaperBadger/builds/70419390

It will be good to understand the reason why Travis CI running the tests differently.

**Comment by aid29** [comment]
I think the "Similarly, we do not provide these values to untrusted builds, triggered by pull requests from another repository." on the page http://docs.travis-ci.com/user/environment-variables/ is the reason.

**Comment by acabunoc** [comment]
@aid29 thanks for the research! We should add the encrypted environment variables to the .travis.yml

http://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables

**Comment by guahanweb** [comment]
Adding encrypted environment variables to the YML file is not difficult, though it would be helpful to have a reference to the variables needed. Any input on which variables and values (assuming API keys) are needed for the builds?

**Comment by acabunoc** [comment]
I can email you the values - abby [at] mozillafoundation.org

Variables:

SESSION_SECRET
BADGES_SYSTEM
BADGES_KEY
BADGES_ENDPOINT
BADGES_SECRET

**Comment by guahanweb** [comment]
OK. There is one other challenge, though: if we do this from a fork, Travis will not use the same encryption keys. So, the task will need to be done by someone with write access to the actual repo. Here's the point of interest in the docs:
> Encryption and decryption keys are tied to the repository. If you fork a project and add it to Travis CI, it will have different keys to the original.

**Comment by guahanweb** [comment]
Also:
> Encrypted environment variables are not available to pull requests from forks due to the security risk of exposing such information to unknown code.

**Comment by acabunoc** [comment]
Ah. I suppose we just won't be able to run tests properly on forks!

I'm glad you read through these docs for us :) Any alternate solutions come to mind?

**Comment by guahanweb** [comment]
@acabunoc: If there were a way to to a Git `post-merge` script to run the travis CLI, each fork could set up its own encrypted keys, but that would probably defeat the purpose of the Travis security model. 

One question does come to mind: how do we just spin up the client service locally and point it to the hosted web service for the data?

**Comment by acabunoc** [comment]
Running locally -

This should get you started:
https://github.com/mozillascience/PaperBadger#getting-started
 -- I'll send you some environment variables you'll need

**Comment by guahanweb** [comment]
OK, cool. If we set up environment variables locally for the fork, we should just set git to assume unchanged on that YML file, and we should be fine:
http://gitready.com/intermediate/2009/02/18/temporarily-ignoring-files.html

**Comment by acabunoc** [comment]
ohh, that sounds like a good solution! Thanks @guahanweb!

I have a head out for a bit -- thanks for your sprint of work here! Very much appreciated :smile:

**Comment by josmas** [comment]
Now that we have separated unit and integration tests, https://github.com/mozillascience/PaperBadger/commit/2502d02465d8bf15852f15b034b32928ca13a4ea changes the travis config to run integration tests only when pushed with write access (which means access to the encrypted variables). Closing this one now; thanks everyone for your help figuring this out!
