### ISSUE TITLE
Add tests for API endpoints

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/PaperBadger#75]
From @aid29:

>I think we need add test for this endpoint as well. Do you have a QA or Dev Badges server environment?

https://github.com/mozillascience/PaperBadger/pull/74#issuecomment-123565229

To do: decide on our testing environment

/cc @audy

**Comment by josmas** [comment]
We now have tests for API endpoints, but they run against the production server, which may not be the best thing to do.

What is the current state of http://badgekit-api-test-sciencelab.herokuapp.com/ ?
I am running the current tests against it and I am getting three errors, most likely cause the data in there is not consistent with the production one (the one with no *-test-* in the URL).
We could sync the two servers and use the *test* one in the `.env` file.

**Comment by josmas** [comment]
ping @acabunoc in case you haven't seen the comment above.

**Comment by acabunoc** [comment]
hey @josmas!  http://badgekit-api-test-sciencelab.herokuapp.com/ is not in maintenance and likely does not have consistent data. Syncing the two and using the test one in .env seems reasonable. A task for #mozsprint?

**Comment by josmas** [comment]
hey @acabunoc yes, this is a good task for the sprint. If we get a dump of the data, and access to the api-test server, we can work on and close both this issue and #65 

We can also replicate this setup with the local server when we move to Badgr, without having to run a test server in the cloud.

**Comment by andreabedini** [comment]
hi @josmas sorry there's too little information to understand what to do :) I got the website running with docker but I am not sure where the data (if there's any) is supposed to come from. Shouldn't an api-test server be included in the docker setup? sorry, I am still trying to understand the setup

**Comment by josmas** [comment]
Hi @andreabedini apologies, it is a bit cryptic indeed. This issue should be taken care of by #195 but it hasn't been reviewed yet.

**Comment by josmas** [comment]
Please update your _.env_ and _docker.env_ files with the new endpoint for the test server in _default.env_. Closing this now.
