### ISSUE TITLE
Add form validation - Publisher interface

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/PaperBadger#76]
Warn a user if:
* DOI is malformed
* email address not valid / not separated by newline

Related to #22

**Comment by guahanweb** [comment]
Does the DOI have to be a resolvable URI or just formatted as such? It would be nice to do a HEAD request and see if there is anything at the location for validation if it indeed has to resolve.

**Comment by acabunoc** [comment]
Good point - yes! Should resolve!

**Comment by guahanweb** [comment]
So... I'm not an expert in React, though I'm hoping to learn it a bit more. However, in doing some preliminary looking at the templates set up, I'm wondering how conducive to true validation things are right now. I'm looking at this, and it seems to be a pretty thorough walkthrough, but it is pretty involved.

http://christianalfoni.github.io/javascript/2014/10/22/nailing-that-validation-with-reactjs.html

If your goal is to have validation, is it something you're willing to consider restructuring template mapping and module definition to do?

**Comment by jinankjain** [comment]
@acabunoc Any updates on the PR?

**Comment by acabunoc** [comment]
Hey @jinankjain! I'll take a look tomorrow, sorry I've been travelling
