### ISSUE TITLE
Add author name to badgeinstances

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/PaperBadger#86]
We currently only store the ORCID for each author. During the issuing process, we can add the Author Name.

This will let the JS snippets display author names (not just ORCID).

- [ ] Stores names when we create badge instance
- [x] Go through current data and add author names

**Comment by acabunoc** [comment]
Ran into problem -- not sure where in badgeinstance to store name? Maybe we should fetch names on the fly via ORCID api?

Will think. Thoughts here appreciated.

**Comment by guahanweb** [comment]
Seems to me that the badges API should return author as a data point in the JSON payload, but I don't see it. That way, the client could simply put it in the model but leave it up to the implementation whether or not to use it. I would think making another call to retrieve the author would be a lot of overhead to a consumer.

**Comment by acabunoc** [comment]
Main difficulty is that we're using badgekit-api to issue the badges:

https://github.com/mozilla/badgekit-api/blob/master/docs/issuing.md

We're able to store the ORCID by formatting it as an email address. But there's no field for 'Name'. We're already running a modified version of badgekit to store the doi - https://github.com/acabunoc/badgekit-api

We could make even more changes, but then we'd be getting further from the open badges standard.

**Comment by omar-abdalla** [comment]
Another option worth consideration, is just like the Altmetrics standard, we could provide an image representing the PaperBadger with a number consisting of total of badges to papers. This could link to your site with a doi. There as you can now you could drill down on all the badges for a paper, by user or badge type. 

Later with the Orcid you can add the author's name too.

**Comment by acabunoc** [comment]
@omar-abdalla - that could be a good solution for now. Thanks for the help :)

I'll see how difficult it would be to add Name to the badgekit model, but if we can't do it in time, we may have to go with your suggestion.

**Comment by Alicole** [comment]
@acabunoc have you managed to come up with a solution to map orcids to author names?

Currently we are linking the orcid id's directly to the user profiles on orcid's site.

**Comment by acabunoc** [comment]
Not yet @Alicole --

I can see two possible approaches:

1. Modify badgekit-api model
2. Fetch the name from the [ORCID Public API](http://members.orcid.org/api/tutorial-retrieve-data-public-api-curl-12-and-earlier) when we return data

I'm not entirely happy with either. Sorry for my indecisiveness here. I'll take a closer look today and update this issue as I go.

**Comment by acabunoc** [comment]
Some work to storing names in badgeInstances in our model

https://github.com/acabunoc/badgekit-api/pull/1

**Comment by acabunoc** [comment]
Added Author names to current database. #97 will add names to each new created badge.

**Comment by wjrsimpson** [comment]
Looks like I might be a bit late, but ORCID think option 2 is better.

2) Fetch the name from the ORCID Public API when we return data

Then you are more likely to have the up-to-date, preferred name for the user and will respect their privacy preferences.

**Comment by Alicole** [comment]
Not all items currently seem to have author names.

Also "name" seems to be being used for a few different classes of elements, which in itself is confusing and makes it difficult to parse.

**Comment by acabunoc** [comment]
Hey @wjrsimpson -- I implemented 1) since it was easier for me right now (I haven't used ORCID's API). We can still update to 2), but I suspect it will be more work than this: #97. Do you have time to get me started on using the orcid api w/ our setup?

@Alicole - where are there no author names? Sorry, I've looked and can't find badges that don't have names right now.

**Comment by Alicole** [comment]
@acabunoc To test the endpoints initially, as we don't have any articles with badges on our test server, we copied the JSON from the endpoint and hosted it locally.

It seems that this contained a merge of the old and new versions, have now addressed this and can see author names for all badges.

**Comment by acabunoc** [comment]
Glad we sorted that out, @Alicole :smile: 

Also, let me know if you have a preferred field name.

**Comment by Alicole** [comment]
@acabunoc in terms of field name, how about "authorName"?

**Comment by acabunoc** [comment]
@Alicole -- that sounds good! I'll have time to make this change later this week :)

**Comment by jinankjain** [comment]
@acabunoc For getting the authorName from orcid we do that by using ORCID API http://members.orcid.org/api/api-calls. Should I move on with this solution?

**Comment by josmas** [comment]
it seems like this is fixed, as names are already being used in the widgets. Please let me know if that is not the case, but closing for now (can reopen if more work is needed).
