### ISSUE TITLE
Add endpoint so that we can query if there are any badges available for a given article or user

### ISSUE THREAD

**Issue by Alicole** [mozillascience/PaperBadger#95]
In order to be able to know if there are badges available, we need has badges functionality.

Preferably also provided as an endpoint, so implementers can query availability. 

Providing a decision point should we apply this functionality or not.

**Comment by acabunoc** [comment]
Makes sense -- can do

**Comment by acabunoc** [comment]
Proposal: add endpoints returning a count of badge instances:

    /users/:orcid/badges/count
    /papers/:doi1/:doi2/badges/count

I can take a look at this

**Comment by Alicole** [comment]
Does this proposal cover single papers too?

**Comment by acabunoc** [comment]
@Alicole - this only covers single papers. `doi1` and `doi2` are the two parts of the doi that we've used for several endpoints.

all badges for a specific paper: [/papers/10.1186/2047-217X-2-10/badges](http://paperbadger.herokuapp.com/papers/10.1186/2047-217X-2-10/badges?pretty=true)

    /papers/:doi1/:doi2/badges

Count of badges for a specific paper: [/papers/10.1186/2047-217X-2-10/badges/count](http://paperbadger.herokuapp.com/papers/10.1186/2047-217X-2-10/badges/count?pretty=true) (this will work when #96 is merged in)

    /papers/:doi1/:doi2/badges/count

**Comment by acabunoc** [comment]
@Alicole - I merged in #96 - let me know if we can close this issue now!
